name: Check Docs Links

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  links:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check README
        uses: becheran/mlc@v0.21.0
        with:
          args: ./README.md -i "https://ulixee.org/*"

      - name: Check Datastore Docs
        uses: becheran/mlc@v0.21.0
        with:
          args: ./datastore/docs -i "https://ulixee.org/*"

      - name: Check Cloud Docs
        uses: becheran/mlc@v0.21.0
        with:
          args: ./cloud/docs -i "https://ulixee.org/*"
