"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Fs = require("fs");
const paths_1 = require("../paths");
const AgentEnv = Fs.readFileSync(require.resolve('@ulixee/unblocked-agent/.env.defaults'), 'utf8');
const MitmEnv = Fs.readFileSync(require.resolve('@ulixee/unblocked-agent-mitm/.env.defaults'), 'utf8');
const HeroEnv = Fs.readFileSync(require.resolve('@ulixee/hero-core').replace(/index.*js/, '.env.defaults'), 'utf8');
const DatastoreEnv = Fs.readFileSync(require.resolve('@ulixee/datastore-core').replace(/index.*js/, '.env.defaults'), 'utf8');
const CloudEnv = Fs.readFileSync(require.resolve('@ulixee/cloud').replace(/index.*js/, `.env.cloud.defaults`), 'utf8');
Fs.writeFileSync(`${paths_1.rootDir}/.env.defaults`, clean(`## AUTOGENERATED ROLLUP OF ULIXEE ENV VARIABLES

### DO NOT EDIT THIS FILE.

## Cloud
${CloudEnv}
## Datastore
${DatastoreEnv}
## Hero
${HeroEnv}
## Agent
${AgentEnv}
## Mitm
${MitmEnv}`));
function clean(env) {
    return env
        .replace(/\n## Sub-tool env settings\n/g, '')
        .replace(/# @ulixee.*\n/g, '');
}
//# sourceMappingURL=gatherEnvSettings.js.map