import * as Fs from 'fs';
import { rootDir } from '../paths';

const AgentEnv = Fs.readFileSync(require.resolve('@ulixee/unblocked-agent/.env.defaults'), 'utf8');
const MitmEnv = Fs.readFileSync(require.resolve('@ulixee/unblocked-agent-mitm/.env.defaults'), 'utf8');
const HeroEnv = Fs.readFileSync(
  require.resolve('@ulixee/hero-core').replace(/index.*js/, '.env.defaults'),
  'utf8',
);
const DatastoreEnv = Fs.readFileSync(
  require.resolve('@ulixee/datastore-core').replace(/index.*js/, '.env.defaults'),
  'utf8',
);
const MinerEnv = Fs.readFileSync(
  require.resolve('@ulixee/miner').replace(/index.*js/, `.env.miner.defaults`),
  'utf8',
);

Fs.writeFileSync(
  `${rootDir}/.env.defaults`,
  clean(`## AUTOGENERATED ROLLUP OF ULIXEE ENV VARIABLES

### DO NOT EDIT THIS FILE.

## Miner
${MinerEnv}
## Datastore
${DatastoreEnv}
## Hero
${HeroEnv}
## Agent
${AgentEnv}
## Mitm
${MitmEnv}`),
);

function clean(env: string): string {
  return env
    .replace(/\n## Sub-tool env settings\n/g, '')
    .replace(/# @ulixee.*\n/g, '')
}
